### ISSUE TITLE
Auto-sync CI status for each package

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint-ecosystem-tester#22]
Currently, the failed packages are managed by hard-coded:

https://github.com/stylelint/stylelint-ecosystem-tester/blob/a64c4f9e0c5c09014c798d9a775dcbf5cc319ecd/scripts/update-readme.js#L10-L25

This way is not smart. We would like to automate updating the README file from CI results.

**Comment by romainmenke** [comment]
Could we use re-usable workflows and have 1 workflow per repo we want to test?
Then each would have its own status and status badge.

-----

We can have helper scripts to (re)generate the workflow files and the badges in the readme.
So that it isn't that much effort when we want to add or remove projects.

**Comment by ybiquitous** [comment]
That sounds great! 👍🏼 

If someone is interested, feel free to open a pull request!
