### ISSUE TITLE
Failing plugin `stylelint-prettier`

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint-ecosystem-tester#61]
See: https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/11714613766/job/32629592702

Both `latest` and `next` are failing, so this is unlikely something we changed.
Possibly a change in `prettier`?

If someone has time and is willing to take a look?

**Comment by Mouvedia** [comment]
https://github.com/prettier/stylelint-prettier/pull/367/files#diff-64ff6bad37ac810ea9c8b48aeba0a89f98c06dee1135c06ca667292449288c5aR117

**Comment by Mouvedia** [comment]
@jeddy3 can you reopen?
If it's not our fault, it should remain open until an issue has been created on their side.

**Comment by BPScott** [comment]
Node v22 got promoted to the LTS version a few weeks back.
https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/11675534073/job/32510262054 was the first stylelint-prettier ecosystem test run to start failing and also the first to use node 22.

In node 22, Prettier v3.2.5 and below raise a node deprecation warning. This was fixed in Prettier v3.3.0.

`stylelint-prettier` tested against Prettier v3.0.0 as the minimum prettier version supported.
The presence of the deprecation warning threw off our e2e tests as running `stylelint --json` no longer produced valid json in stderr - as the deprecation warning was also included.




In https://github.com/prettier/stylelint-prettier/pull/377 I've added node v22 to stylelint-prettier's CI config and updated the version of prettier that we use for tests to v3.3.0.

The ecosystem tests should pass now.

**Comment by ybiquitous** [comment]
@BPScott Thanks for telling us! The tests have been recovered ✅ 

- latest: https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/12208545897
- next: https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/12208628586
